### ISSUE TITLE
Different span behavior for Spring WebMCV re static/deferred attach

### ISSUE THREAD

**Issue by safris** [opentracing-contrib/java-specialagent#358]
The latest changes to Static Deferred Attach have enabled it to be turned on for all integration tests. Now, Spring WebMVC 3.0.2, 3.2.18, 4.0.0, and 4.3.25 test is failing, reporting extra spans when Static Deferred Attach is activated. Spring WebMVC 5.0.0 and 5.2.1 are working consistently in both modes.

To work around this issue, the following has been added to the POMs for tests of Spring WebMVC 3.0.2, 3.2.18, 4.0.0, and 4.3.25:
```
<sa.itest.args>-Dsa.init.defer=false</sa.itest.args>
```

Here are the spans with Static Attach:
```
Spans: [{traceId:9, spanId:10, parentId:0, operationName:"GET"}, {traceId:9, spanId:11, parentId:10, operationName:"GET"}]
Span: {traceId:9, spanId:10, parentId:0, operationName:"GET"}
  Component: http-url-connection
  Tags: {http.status_code=200, component=http-url-connection, http.url=http://localhost:8080, peer.hostname=localhost, peer.port=8080, http.method=GET}
  Logs: 
Span: {traceId:9, spanId:11, parentId:10, operationName:"GET"}
  Component: java-web-servlet
  Tags: {http.url=http://localhost:8080/, http.status_code=200, component=java-web-servlet, span.kind=server, http.method=GET}
  Logs: 
  {event=preHandle, handler.class_simple_name=HelloController}
  {event=afterCompletion, handler.class_simple_name=HelloController}
```

Here are the spans with Static Deferred Attach:
```
Spans: [{traceId:1, spanId:3, parentId:2, operationName:"GET"}, {traceId:1, spanId:2, parentId:0, operationName:"GET"}, {traceId:1, spanId:4, parentId:3, operationName:"GET"}]
Span: {traceId:1, spanId:3, parentId:2, operationName:"GET"}
  Component: java-web-servlet
  Tags: {http.url=http://localhost:8080/, http.status_code=200, component=java-web-servlet, span.kind=server, http.method=GET}
  Logs: 
Span: {traceId:1, spanId:2, parentId:0, operationName:"GET"}
  Component: http-url-connection
  Tags: {http.status_code=200, component=http-url-connection, http.url=http://localhost:8080, peer.hostname=localhost, peer.port=8080, http.method=GET}
  Logs: 
Span: {traceId:1, spanId:4, parentId:3, operationName:"GET"}
  Component: null
  Tags: {}
  Logs: 
  {event=preHandle, handler.class_simple_name=HelloController}
  {event=afterCompletion, handler.class_simple_name=HelloController}
```

Here is the intercept log for static attach:
```
-------> Intercept [qtp1144702392-15] from: protected void javax.servlet.http.HttpServlet.service(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws javax.servlet.ServletException,java.io.IOException
-------> Intercept [qtp1144702392-15] from: public org.springframework.web.servlet.HandlerInterceptor[] org.springframework.web.servlet.HandlerExecutionChain.getInterceptors()
-------> Intercept [qtp1144702392-15] from: public org.springframework.web.servlet.HandlerInterceptor[] org.springframework.web.servlet.HandlerExecutionChain.getInterceptors()
```

Note `qtp1144702392-15` is the thread name.

Here is the intercept log for static deferred attach:
```
-------> Intercept [qtp1212191909-16] from: protected void javax.servlet.http.HttpServlet.service(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws javax.servlet.ServletException,java.io.IOException
-------> Intercept [qtp1212191909-16] from: public org.springframework.web.servlet.HandlerInterceptor[] org.springframework.web.servlet.HandlerExecutionChain.getInterceptors()
-------> Intercept [qtp1212191909-16] from: public org.springframework.web.servlet.HandlerInterceptor[] org.springframework.web.servlet.HandlerExecutionChain.getInterceptors()
```
Note `qtp1212191909-16` is the thread name.

**The deliverable for the completion of this issue is the removal of**
**`<sa.itest.args>-Dsa.init.defer=false</sa.itest.args>`**
**from the POMs of test for Spring WebMVC 3.0.2, 3.2.18, 4.0.0, and 4.3.25.**
